USE employee_Tracker_db;
INSERT INTO department (NAME) values ("Engineering");    
 INSERT INTO department (NAME) values ("Law");
 INSERT INTO department (NAME) values ("Manager");  
 INSERT INTO department (NAME) values ("Manager");
 INSERT INTO department (NAME) values ("IT");
 INSERT INTO department (NAME) values ("Accountant");
INSERT INTO role (title, salary, department_id) values ("Engineer", 70,000 ,22);
 INSERT INTO role (title, salary, department_id) values ("Engineer", 75,000,34);    
 INSERT INTO role (title, salary, department_id) values ("Attorney", 150,000,45);
 INSERT INTO role (title, salary, department_id) values ("Manager",  95,000,11);  
 INSERT INTO role (title, salary, department_id) values ("Manager", 96,000,66);
 INSERT INTO role (title, salary, department_id) values ("Programmer", 100,000,65);
 INSERT INTO role (title, salary, department_id) values ("Accountant", 90,000,90);
INSERT INTO employee(first_name, last_name, role_id ) values ("DWAYNE"  "OLVERA" ,11);
 INSERT INTO employee(first_name, last_name, role_id ) values ("BRANDON", "HUEY",22);    
 INSERT INTO employee(first_name, last_name, role_id ) values ("ELIZABETH", "BROWN",33);
 INSERT INTO employee(first_name, last_name, role_id ) values ("CARMEN",  "OWENS",44);  
 INSERT INTO employee(first_name, last_name, role_id ) values ("SETH", "HANNON",55);
 INSERT INTO employee(first_name, last_name, role_id ) values ("ZANE", "THOMAS",66);
 INSERT INTO employee(first_name, last_name, role_id ) values ("ELAN", "MUSK"  ,77);